### ISSUE TITLE
Add `--enable-cbc-parallel` to enable multiple threads

### ISSUE THREAD

**Issue by lsorber** [conda-forge/coincbc-feedstock#18]
Add `--enable-cbc-parallel` in `build.sh` to enable the CBC `threads` parameter (disabled by default). Using multiple threads to explore the tree can significantly improve performance in some cases.

Also, using the OpenBLAS-optimized version of LAPACK (bundled with OpenBLAS) as suggested in #16 could improve performance as well.

**Comment by lsorber** [comment]
Fixed by #19.

**Comment by AaronHolm** [comment]
I installed on a linux VM just a few days ago, but using CBC with Pyomo only utilizes a single CPU in solves and doesn't appear to be taking advantage of the CBC threads parameter. Any suggestions on how to enable this?
